### ISSUE TITLE
编译出错，提示如下

### ISSUE THREAD

**Issue by xiao233ming** [chenjiandongx/mzitu#1]
Traceback (most recent call last):
  File "E:\PY_TEST\mzitu_analysis.py", line 12, in <module>
    jieba.load_userdict(r"E:\jieba.txt")
  File "D:\Python3.6.1\lib\site-packages\jieba\__init__.py", line 374, in load_u
serdict
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\jieba.txt'

**Comment by chenjiandongx** [comment]
jieba.txt是自己定义的分词，已上传到data文件夹中，拉到自己项目的路径下就可以
